public class GameJFrame extends javax.swing.JFrame {
    
    private static final String style1 = "javax.swing.plaf.metal.MetalLookAndFeel";
    private static final String style2 = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
    private static final String style3 = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
    
    private int guessedNumber, min, max;
    private Game game;
    
    public GameJFrame() {
        initComponents();
        addRadioButtonsToGroup();
        changeStyle(style1);

        
        enableStart();
        disableGame();
    }
    
    private void addRadioButtonsToGroup() {
        rbStyleGroup.add(rbStyle1);
        rbStyleGroup.add(rbStyle2);
        rbStyleGroup.add(rbStyle3);
        
        rbStyle1.setSelected(true);
    }
    private void changeStyle(String actionCommand) {
        try {
            String style = style1;
            switch (actionCommand) {
                case "style1":
                    style = style1;
                    break;
                case "style2":
                    style = style2;
                    break;
                case "style3":
                    style = style3;
                    break;
                default:
                    style = style1;
                    break;
            }

            javax.swing.UIManager.setLookAndFeel(style);
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        } catch (Exception exc) {
            taErr.append(exc.getMessage());
            taErr.append(System.lineSeparator());
        }
    }

    private void createGame() {
        min = (int) spinMin.getValue();
        max = (int) spinMax.getValue();
        game = new Game(min, max);
    }
      
    private void guess() {
        disableStart();
        enableGame();

        try {
            game.setMin(min);
            game.setMax(max);
        } catch (Exception exc) {
            taErr.append(exc.getMessage());
            taErr.append(System.lineSeparator());
            disableGame();
            enableStart();
            return;
        }

        guessedNumber = game.guess();

        taGame.selectAll();
        taGame.replaceSelection("");
        taGame.append("Ваше число  ");
        taGame.append(Integer.toString(guessedNumber));
        taGame.append(" ?");
        taGame.append(System.lineSeparator());
    }
    
    private void disableStart() {
        spinMin.setEnabled(false);
        spinMin.setEnabled(false);
        btnStart.setEnabled(false);
        spinMax.setEnabled(false);
        spinMin.setEnabled(false);
    }
     private void enableStart() {
        spinMin.setEnabled(true);
        spinMin.setEnabled(true);
        btnStart.setEnabled(true);
        spinMax.setEnabled(true);
        spinMin.setEnabled(true);
    }
    private void disableGame() {
        btnLess.setEnabled(false);
        btnCorrect.setEnabled(false);
        btnMore.setEnabled(false);
    }
    private void enableGame() {
        btnLess.setEnabled(true);
        btnCorrect.setEnabled(true);
        btnMore.setEnabled(true);
    }
    
    private void guessed() {
        disableGame();
        enableStart();
        taGame.append("Победа! Вы загадали число " + Integer.toString(guessedNumber));
        taGame.append(System.lineSeparator());
        taGame.append("Чтобы сыграть еще раз нажмите НАЧАТЬ.");
        taGame.append(System.lineSeparator());
    }
     private void guessLess() {
        if (min >= max) {
            cheat();
        } else {
            final int newMax = guessedNumber - 1;
            max = newMax;
            guess();
        }
    }
     
    private void guessMore() {
        if (min >= max) {
            cheat();
        } else {
            final int newMin = guessedNumber + 1;
            min = newMin;
            guess();
        }
    }
    
    private void cheat() {
        disableGame();
        enableStart();
        taGame.append("Вы жульничаете!");
        taGame.append(System.lineSeparator());
        taGame.append("Чтобы сыграть еще раз нажмите НАЧАТЬ.");
        taGame.append(System.lineSeparator());
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbStyleGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taGame = new javax.swing.JTextArea();
        btnLess = new javax.swing.JButton();
        btnCorrect = new javax.swing.JButton();
        btnMore = new javax.swing.JButton();
        rbStyle1 = new javax.swing.JRadioButton();
        rbStyle2 = new javax.swing.JRadioButton();
        rbStyle3 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taErr = new javax.swing.JTextArea();
        spinMax = new javax.swing.JSpinner();
        spinMin = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Выберите границы диапазона чисел.");

        jLabel2.setText("Минимальное число:");

        jLabel3.setText("Максимальное число:");

        btnStart.setText("Начать");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        taGame.setColumns(20);
        taGame.setRows(5);
        jScrollPane1.setViewportView(taGame);

        btnLess.setText("Меньше");
        btnLess.setEnabled(false);
        btnLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLessActionPerformed(evt);
            }
        });

        btnCorrect.setText("Угадал");
        btnCorrect.setEnabled(false);
        btnCorrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrectActionPerformed(evt);
            }
        });

        btnMore.setText("Больше");
        btnMore.setEnabled(false);
        btnMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreActionPerformed(evt);
            }
        });

        rbStyle1.setText("javax.swing.plaf.metal.MetalLookAndFeel");
        rbStyle1.setActionCommand("style1");
        rbStyle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbStyle1ActionPerformed(evt);
            }
        });

        rbStyle2.setText("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        rbStyle2.setActionCommand("style2");
        rbStyle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbStyle2ActionPerformed(evt);
            }
        });

        rbStyle3.setText("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        rbStyle3.setActionCommand("style3");
        rbStyle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbStyle3ActionPerformed(evt);
            }
        });

        taErr.setColumns(20);
        taErr.setRows(5);
        jScrollPane2.setViewportView(taErr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinMin, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinMax, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbStyle2)
                                            .addComponent(rbStyle1)
                                            .addComponent(rbStyle3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLess, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)))
                                .addComponent(btnMore, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(spinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLess)
                    .addComponent(btnCorrect)
                    .addComponent(btnMore))
                .addGap(18, 18, 18)
                .addComponent(rbStyle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbStyle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbStyle3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        createGame();
        guess();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreActionPerformed
        // TODO add your handling code here:
        guessMore();
    }//GEN-LAST:event_btnMoreActionPerformed

    private void btnLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLessActionPerformed
        // TODO add your handling code here:
        guessLess();
    }//GEN-LAST:event_btnLessActionPerformed

    private void btnCorrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrectActionPerformed
        // TODO add your handling code here:
        guessed();
    }//GEN-LAST:event_btnCorrectActionPerformed

    private void rbStyle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbStyle1ActionPerformed
        // TODO add your handling code here:
         changeStyle(rbStyleGroup.getSelection().getActionCommand());
    }//GEN-LAST:event_rbStyle1ActionPerformed

    private void rbStyle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbStyle3ActionPerformed
        // TODO add your handling code here:
        changeStyle(rbStyleGroup.getSelection().getActionCommand());
    }//GEN-LAST:event_rbStyle3ActionPerformed

    private void rbStyle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbStyle2ActionPerformed
        // TODO add your handling code here:
        changeStyle(rbStyleGroup.getSelection().getActionCommand());
    }//GEN-LAST:event_rbStyle2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCorrect;
    private javax.swing.JButton btnLess;
    private javax.swing.JButton btnMore;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbStyle1;
    private javax.swing.JRadioButton rbStyle2;
    private javax.swing.JRadioButton rbStyle3;
    private javax.swing.ButtonGroup rbStyleGroup;
    private javax.swing.JSpinner spinMax;
    private javax.swing.JSpinner spinMin;
    private javax.swing.JTextArea taErr;
    private javax.swing.JTextArea taGame;
    // End of variables declaration//GEN-END:variables
}
